apiVersion: apps/v1
kind: Deployment
metadata:
  name: journal-app
  labels:
    app: journal
spec:
  replicas: 2
  selector:
    matchLabels:
      app: journal
  template:
    metadata:
      labels:
        app: journal
    spec:
      containers:
        - name: journal
          image: rajat1611/journal-app:8
          ports:
            - name: http
              containerPort: 5000
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
