apiVersion: v1
kind: Service
metadata:
  name: journal-service
spec:
  type: NodePort
  selector:
    app: journal
  ports:
  - name: http
    port: 80          # Service port (inside cluster)
    targetPort: 5000  # Container port
    nodePort: 30080   # Optional; must be 30000â€“32767
